services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - live:/usr/share/nginx/hls
      - nginx-logs:/var/log/nginx
    ports:
      - "1935:1935/tcp"
      - "8080:80/tcp"
    configs:
      - source: nginx-config
        target: /etc/nginx/nginx.conf
    networks:
      - auth-network

  auth:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    configs:
      - source: auth-config
        target: /vrstream.yml
    networks:
      - auth-network

configs:
  nginx-config:
    file: ./nginx.conf
  auth-config:
    file: ./vrstream.yml

volumes:
  live:
  nginx-logs:

networks:
  auth-network:
